### utils ###
[[repositories]]
git-url = "git@github.com:mirrorboards/mirrorboards-vscode.git"
path = ".vscode"

[[repositories]]
git-url = "git@github.com:mirrorboards/mirrorboards-bin.git"
path = "bin"
branch = "configs/lunacrafts"

[[repositories]]
git-url = "git@github.com:mirrorboards/mirrorboards-legacy.git"
path = ".legacy"

### estateboards ###
[[repositories]]
git-url = "git@github.com:estateboards/whitepapers.git"
path = "estateboards/whitepapers"

### pay2vault ###
[[repositories]]
git-url = "git@github.com:pay2vault/pay2vault-api-proto.git"
path = "pay2vault/pay2vault-api-proto"

[[repositories]]
git-url = "git@github.com:pay2vault/pay2vault-api.git"
path = "pay2vault/pay2vault-api"

[[repositories]]
git-url = "git@github.com:pay2vault/api.git"
path = "pay2vault/pay2vault-api-next"

[[repositories]]
git-url = "git@github.com:pay2vault/pay2vault-notes.git"
path = "pay2vault/pay2vault-notes"

[[repositories]]
git-url = "git@github.com:pay2vault/pay2vault-web.git"
path = "pay2vault/pay2vault-web"

### mirrorboards ###
[[repositories]]
git-url = "git@github.com:mirrorboards/mirrorboards-pulumi-utils.git"
path = "mirrorboards/mirrorboards-pulumi-utils"

[[repositories]]
git-url = "git@github.com:mirrorboards/mirrorboards-mctl.git"
path = "mirrorboards/mirrorboards-mctl"

[[repositories]]
git-url = "git@github.com:mirrorboards/mirrorboards-mctl.git"
path = "mirrorboards/mirrorboards-mctl-v2"

[[repositories]]
git-url = "git@github.com:mirrorboards/mirrorboards-roo-flow.git"
path = "mirrorboards/mirrorboards-roo-flow"

[[repositories]]
git-url = "git@github.com:mirrorboards/mirrorboards-roo-sparc.git"
path = "mirrorboards/mirrorboards-roo-sparc"

[[repositories]]
git-url = "git@github.com:mirrorboards/mirrorboards-roo-modes.git"
path = "mirrorboards/mirrorboards-roo-modes"

[[repositories]]
git-url = "git@github.com:mirrorboards/mirrorboards-notes.git"
path = ".notes"

[[repositories]]
git-url = "git@github.com:mirrorboards/mirrorboards-fish-functions.git"
path = "mirrorboards/mirrorboards-fish-functions"

### platform ###
[[repositories]]
git-url = "git@github.com:pay2vault/pay2vault-platform.git"
path = "platform/platform-pay2vault"

[[repositories]]
git-url = "git@github.com:mirrorboards/platform.git"
path = "platform/platform-mirrorboards"

[[repositories]]
git-url = "git@github.com:pay2exchange/pay2exchange-platform.git"
path = "platform/platform-pay2exchange"

### pay2exchange ###
[[repositories]]
git-url = "git@github.com:pay2exchange/pay2exchange-notes.git"
path = "pay2exchange/.notes"

[[repositories]]
git-url = "git@github.com:pay2exchange/pay2exchange-smart-contract.git"
path = "pay2exchange/pay2exchange-smart-contract"

[[repositories]]
git-url = "git@github.com:pay2exchange/fast-compiling.git"
path = "pay2exchange/pay2exchange-fast-compiling"

[[repositories]]
git-url = "git@github.com:pay2exchange/pay2exchange-js-ws.git"
path = "pay2exchange/pay2exchange-js-ws"

[[repositories]]
git-url = "git@github.com:pay2exchange/pay2exchange-js.git"
path = "pay2exchange/pay2exchange-js"

[[repositories]]
git-url = "git@github.com:pay2exchange/pay2exchange-report.git"
path = "pay2exchange/pay2exchange-report"

[[repositories]]
git-url = "git@github.com:pay2exchange/pay2exchange-core.git"
path = "pay2exchange/pay2exchange-core"

[[repositories]]
git-url = "git@github.com:pay2exchange/pay2exchange-ees.git"
path = "pay2exchange/pay2exchange-ees"

[[repositories]]
git-url = "git@github.com:pay2exchange/pay2exchange-portal.git"
path = "pay2exchange/pay2exchange-portal"

[[repositories]]
git-url = "git@github.com:pay2exchange/pay2exchange-genesis.git"
path = "pay2exchange/pay2exchange-genesis"

[[repositories]]
git-url = "git@github.com:pay2vault/graphene-rs.git"
path = "pay2vault-vibe/graphene-rs"

[[repositories]]
git-url = "git@github.com:mirrorboards/mirrorboards-genesis-gen.git"
path = "pay2vault-vibe/genesis-gen"

[[repositories]]
git-url = "git@github.com:mirrorboards/mirrorboards-graphene-rs.git"
path = "mirrorboards/mirrorboards-graphene-rs"

# [[repositories]]
# git-url = "git@github.com:bitshares/bitsharesjs.git"
# path = "pay2vault-vibe/graphene-rs/examples/bitsharesjs"

# [[repositories]]
# git-url = "git@github.com:R-Squared-Project/R-Squared-js.git"
# path = "pay2vault-vibe/graphene-rs/examples/R-Squared-js"

# [[repositories]]
# git-url = "git@github.com:pay2exchange/ws-pp-library.git"
# path = "pay2exchange/ws-pp-library"

# [[repositories]]
# git-url = "git@github.com:pay2exchange/secp256k1-zkp.git"
# path = "pay2exchange/secp256k1-zkp"

# R-Squared-Project

[[repositories]]
git-url = "git@github.com:R-Squared-Project/R-Squared-portal.git"
path = "x-github-mirror/R-Squared-Project/R-Squared-portal"

[[repositories]]
git-url = "git@github.com:R-Squared-Project/EES.git"
path = "x-github-mirror/R-Squared-Project/EES"

[[repositories]]
git-url = "git@github.com:R-Squared-Project/R-Squared-core.git"
path = "x-github-mirror/R-Squared-Project/R-Squared-core"

[[repositories]]
git-url = "git@github.com:R-Squared-Project/R-Squared-report.git"
path = "x-github-mirror/R-Squared-Project/R-Squared-report"

[[repositories]]
git-url = "git@github.com:R-Squared-Project/R-Squared-js.git"
path = "x-github-mirror/R-Squared-Project/R-Squared-js"

[[repositories]]
git-url = "git@github.com:R-Squared-Project/R-Squaredjs-ws.git"
path = "x-github-mirror/R-Squared-Project/R-Squaredjs-ws"

[[repositories]]
git-url = "git@github.com:R-Squared-Project/SmartContract.git"
path = "x-github-mirror/R-Squared-Project/SmartContract"

# Bitshares

[[repositories]]
git-url = "git@github.com:bitshares/bitshares-ui.git"
path = "x-github-mirror/bitshares/bitshares-ui"

[[repositories]]
git-url = "git@github.com:bitshares/bitsharesjs.git"
path = "x-github-mirror/bitshares/bitsharesjs"

[[repositories]]
git-url = "git@github.com:bitshares/bitshares-core.git"
path = "x-github-mirror/bitshares/bitshares-core"

[[repositories]]
git-url = "git@github.com:bitshares/bsips.git"
path = "x-github-mirror/bitshares/bsips"

[[repositories]]
git-url = "git@github.com:bitshares/nodejs-faucet.git"
path = "x-github-mirror/bitshares/nodejs-faucet"

[[repositories]]
git-url = "git@github.com:bitshares/bitshares-core.git"
path = "x-github-mirror/bitshares/bitshares-core"

# graphene-rs
[[repositories]]
git-url = "git@github.com:bitshares/bitsharesjs.git"
path = "x-github-mirror/graphene-rs/examples/bitsharesjs"

[[repositories]]
git-url = "git@github.com:R-Squared-Project/R-Squared-js.git"
path = "x-github-mirror/graphene-rs/examples/R-Squared-js"

[[repositories]]
git-url = "git@github.com:pulumi/pulumi-docker.git"
path = "x-github-mirror/pulumi/pulumi-docker"
