[[repositories]]
origin = "git@github.com:example/repo1-updated.git"
branch = "main"
branch-lock = false
path = "example/repo1"
tags = ["example", "updated"]

[[repositories]]
id = "repo2-id"
origin = "git@github.com:example/repo2.git"
branch = "develop"
branch-lock = true
path = "example/repo2"
tags = ["example", "locked"]
