use crate::error::{ConfigError, ConfigResult};
use crate::models::{MirrorConfig, Repository};
use std::fs;
use std::path::{Path, PathBuf};

/// Configuration file manager for mirror.toml files
pub struct ConfigManager {
    file_path: PathBuf,
}

impl ConfigManager {
    /// Create a new config manager for the specified file path
    pub fn new<P: AsRef<Path>>(file_path: P) -> Self {
        ConfigManager {
            file_path: file_path.as_ref().to_path_buf(),
        }
    }
    
    /// Create a config manager for mirror.toml in the current directory
    pub fn default() -> Self {
        ConfigManager::new("mirror.toml")
    }
    
    /// Load configuration from the file
    pub fn load(&self) -> ConfigResult<MirrorConfig> {
        MirrorConfig::load_from_file(&self.file_path)
    }
    
    /// Save configuration to the file
    pub fn save(&self, config: &MirrorConfig) -> ConfigResult<()> {
        config.save_to_file(&self.file_path)
    }
    
    /// Check if the configuration file exists
    pub fn exists(&self) -> bool {
        self.file_path.exists()
    }
    
    /// Get the file path
    pub fn path(&self) -> &Path {
        &self.file_path
    }
    
    /// Create an empty configuration file
    pub fn create_empty(&self) -> ConfigResult<()> {
        let empty_config = MirrorConfig::new();
        self.save(&empty_config)
    }
    
    /// Add a repository to the configuration
    pub fn add_repository(&self, repo: Repository) -> ConfigResult<()> {
        let mut config = if self.exists() {
            self.load()?
        } else {
            MirrorConfig::new()
        };
        
        config.add_repository(repo).map_err(|e| ConfigError::ValidationError {
            message: e.to_string(),
        })?;
        
        self.save(&config)
    }
    
    /// Remove a repository by hash
    pub fn remove_repository(&self, hash: &str) -> ConfigResult<Repository> {
        let mut config = self.load()?;
        
        let removed = config.remove_repository(hash)
            .ok_or_else(|| ConfigError::RepositoryNotFound {
                hash: hash.to_string(),
            })?;
        
        self.save(&config)?;
        Ok(removed)
    }
    
    /// Find a repository by hash
    pub fn find_repository(&self, hash: &str) -> ConfigResult<Option<Repository>> {
        let config = self.load()?;
        Ok(config.find_by_hash(hash).cloned())
    }
    
    /// List all repositories
    pub fn list_repositories(&self) -> ConfigResult<Vec<Repository>> {
        let config = self.load()?;
        Ok(config.repositories().to_vec())
    }
}

impl MirrorConfig {
    /// Load configuration from a TOML file
    pub fn load_from_file<P: AsRef<Path>>(path: P) -> ConfigResult<Self> {
        let path_ref = path.as_ref();
        
        if !path_ref.exists() {
            return Err(ConfigError::FileNotFound {
                path: path_ref.to_path_buf(),
            });
        }
        
        let content = fs::read_to_string(path_ref)?;
        
        if content.trim().is_empty() {
            // Empty file is treated as empty configuration
            return Ok(MirrorConfig::new());
        }
        
        let config: MirrorConfig = toml::from_str(&content)?;
        
        // Validate the loaded configuration
        config.validate().map_err(|e| ConfigError::ValidationError {
            message: e.to_string(),
        })?;
        
        Ok(config)
    }
    
    /// Save configuration to a TOML file
    pub fn save_to_file<P: AsRef<Path>>(&self, path: P) -> ConfigResult<()> {
        let path_ref = path.as_ref();
        
        // Create parent directories if they don't exist
        if let Some(parent) = path_ref.parent() {
            fs::create_dir_all(parent)?;
        }
        
        // Validate before saving
        self.validate().map_err(|e| ConfigError::ValidationError {
            message: e.to_string(),
        })?;
        
        let toml_content = if self.repositories.is_empty() {
            // Create a template for empty configurations with empty repositories array
            String::from(r#"# Mirror Configuration File
#
# This file defines git repositories to be managed by mctl.
#
# Example repository configuration:
# [[repositories]]
# git = "git@github.com:org/repo.git"
# path = "org/repo"
# branch = "main"
# skip-push = false

repositories = []
"#)
        } else {
            // Serialize the configuration with custom formatting
            let mut content = String::from("# Mirror Configuration File\n# Generated by mctl\n\n");
            
            for repo in &self.repositories {
                content.push_str("[[repositories]]\n");
                content.push_str(&format!("git = \"{}\"\n", repo.git));
                content.push_str(&format!("path = \"{}\"\n", repo.path));
                
                // Only include non-default values
                if repo.branch != "main" {
                    content.push_str(&format!("branch = \"{}\"\n", repo.branch));
                }
                
                if repo.skip_push {
                    content.push_str("skip-push = true\n");
                }
                
                content.push('\n');
            }
            
            content
        };
        
        // Write atomically by using a temporary file
        let temp_path = path_ref.with_extension("tmp");
        fs::write(&temp_path, toml_content)?;
        
        // Atomic move
        fs::rename(&temp_path, path_ref)?;
        
        Ok(())
    }
    
    /// Create a backup of the configuration file
    pub fn backup_file<P: AsRef<Path>>(path: P) -> ConfigResult<PathBuf> {
        let path_ref = path.as_ref();
        
        if !path_ref.exists() {
            return Err(ConfigError::FileNotFound {
                path: path_ref.to_path_buf(),
            });
        }
        
        let timestamp = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_secs();
        
        let backup_path = path_ref.with_extension(format!("toml.backup.{}", timestamp));
        fs::copy(path_ref, &backup_path)?;
        
        Ok(backup_path)
    }
    
    /// Merge another configuration into this one
    pub fn merge(&mut self, other: &MirrorConfig) -> ConfigResult<()> {
        for repo in &other.repositories {
            // Check if repository already exists by git URL
            if !self.repositories.iter().any(|r| r.git == repo.git) {
                self.add_repository(repo.clone()).map_err(|e| ConfigError::ValidationError {
                    message: e.to_string(),
                })?;
            }
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::NamedTempFile;

    #[test]
    fn test_load_empty_file() {
        let temp_file = NamedTempFile::new().unwrap();
        
        let config = MirrorConfig::load_from_file(temp_file.path()).unwrap();
        assert!(config.is_empty());
    }
    
    #[test]
    fn test_save_and_load_config() {
        let temp_file = NamedTempFile::new().unwrap();
        
        let mut config = MirrorConfig::new();
        let repo = Repository::new(
            "git@github.com:org/repo.git".to_string(),
            "org/repo".to_string(),
            Some("main".to_string()),
            Some(false),
        );
        config.add_repository(repo.clone()).unwrap();
        
        config.save_to_file(temp_file.path()).unwrap();
        
        let loaded_config = MirrorConfig::load_from_file(temp_file.path()).unwrap();
        assert_eq!(loaded_config.len(), 1);
        assert_eq!(loaded_config.repositories()[0], repo);
    }
    
    #[test]
    fn test_config_manager() {
        let temp_file = NamedTempFile::new().unwrap();
        let temp_path = temp_file.path().to_path_buf();
        
        // Delete the temp file so we can test creation
        drop(temp_file);
        
        let manager = ConfigManager::new(&temp_path);
        assert!(!manager.exists());
        
        manager.create_empty().unwrap();
        assert!(manager.exists());
        
        let repo = Repository::new(
            "git@github.com:org/repo.git".to_string(),
            "org/repo".to_string(),
            None,
            None,
        );
        
        manager.add_repository(repo.clone()).unwrap();
        
        let repos = manager.list_repositories().unwrap();
        assert_eq!(repos.len(), 1);
        assert_eq!(repos[0].git, repo.git);
        
        let hash = repo.compute_hash();
        let found = manager.find_repository(&hash[..4]).unwrap();
        assert!(found.is_some());
        
        let removed = manager.remove_repository(&hash[..4]).unwrap();
        assert_eq!(removed.git, repo.git);
        
        let repos_after = manager.list_repositories().unwrap();
        assert!(repos_after.is_empty());
    }
    
    #[test]
    fn test_toml_format() {
        let temp_file = NamedTempFile::new().unwrap();
        
        let mut config = MirrorConfig::new();
        let repo1 = Repository::new(
            "git@github.com:org/repo1.git".to_string(),
            "org/repo1".to_string(),
            Some("main".to_string()),
            Some(false),
        );
        let repo2 = Repository::new(
            "https://github.com:org/repo2.git".to_string(),
            "org/repo2".to_string(),
            Some("develop".to_string()),
            Some(true),
        );
        
        config.add_repository(repo1).unwrap();
        config.add_repository(repo2).unwrap();
        
        config.save_to_file(temp_file.path()).unwrap();
        
        let content = fs::read_to_string(temp_file.path()).unwrap();
        
        // Check that the content contains expected elements
        assert!(content.contains("[[repositories]]"));
        assert!(content.contains("git@github.com:org/repo1.git"));
        assert!(content.contains("https://github.com:org/repo2.git"));
        assert!(content.contains("path = \"org/repo1\""));
        assert!(content.contains("path = \"org/repo2\""));
        assert!(content.contains("branch = \"develop\"")); // Non-default branch
        assert!(content.contains("skip-push = true")); // Non-default skip-push
        
        // Default values should not be explicitly written
        assert!(!content.contains("branch = \"main\""));
        assert!(!content.contains("skip-push = false"));
    }
    
    #[test]
    fn test_backup_functionality() {
        let temp_file = NamedTempFile::new().unwrap();
        let config = MirrorConfig::new();
        config.save_to_file(temp_file.path()).unwrap();
        
        let backup_path = MirrorConfig::backup_file(temp_file.path()).unwrap();
        assert!(backup_path.exists());
        
        // Backup should have same content
        let original_content = fs::read_to_string(temp_file.path()).unwrap();
        let backup_content = fs::read_to_string(&backup_path).unwrap();
        assert_eq!(original_content, backup_content);
        
        // Clean up
        fs::remove_file(backup_path).unwrap();
    }
    
    #[test]
    fn test_merge_configurations() {
        let mut config1 = MirrorConfig::new();
        let mut config2 = MirrorConfig::new();
        
        let repo1 = Repository::new(
            "git@github.com:org/repo1.git".to_string(),
            "org/repo1".to_string(),
            None,
            None,
        );
        let repo2 = Repository::new(
            "git@github.com:org/repo2.git".to_string(),
            "org/repo2".to_string(),
            None,
            None,
        );
        
        config1.add_repository(repo1).unwrap();
        config2.add_repository(repo2).unwrap();
        
        config1.merge(&config2).unwrap();
        
        assert_eq!(config1.len(), 2);
        assert!(config1.find_by_git_url("git@github.com:org/repo1.git").is_some());
        assert!(config1.find_by_git_url("git@github.com:org/repo2.git").is_some());
    }
}